import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React from "react";
import Navbar from "@/components/Nav";
import TrpcProvider from "@/Providers/TrpcProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <main className={"relative flex flex-col min-h-screen"}>
          <TrpcProvider>
            <Navbar />
            <div className={"flex-grow flex-1"}>{children}</div>
          </TrpcProvider>
        </main>
      </body>
    </html>
  );
}
